jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Publish to GitHub Packages using Apache Maven
      run: mvn --batch-mode deploy -P publish-on-github-packages
name: Maven Package
on:
  repository_dispatch:
    types: trigger-ga___maven-publish.yml
